[env]
TERM = "alacritty"

[font]
size = 14.0

[font.normal]
family = "DejaVuSansMono Nerd Font"
style = "Regular"

[window]
decorations = "full"
opacity = 1.0

[window.dimensions]
columns = 120
lines = 30
